# docker-compose.yml
version: "3"
services:
  app:
    build: .
    ports:
      - "8076:8010"
    volumes:
      - ./src:/app/src
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    runtime: nvidia
    mem_limit: 5g 
    networks:
      - pythonapi_default
networks:
  pythonapi_default:
    external: true